title: Rey's Tech Blog
name: Rey's Tech Blog
description: >-
  This is a blog of someone passionate about technology who wants to share some of the things he knows
  about Application Development, Integration, Cloud, Big Data and Digital Transformation
baseurl: ""
url: "https://yolofordream.github.io/"
repository: "YoloForDream/YoloForDream.github.io"
github_username: YoloForDream

paginate: 10
paginate_path: "/page/:num/"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
include: ["_pages"]
permalink: /posts/:title/
excerpt_separator: <!--more-->
author:
  name: Rey Wang
  github: YoloForDream
  linkedin: rey-wang
  twitter: yolofordream

host: 0.0.0.0