disqus:
  comments: false
  disqus_shortname: 'yolofordream'

utterances:
  enabled: true
  repo: 'YoloForDream/YoloForDream.github.io'
  issue_term: 'pathname'
  theme: 'github-light'

google-ID: 'UA-91332049-1'

menu:
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/YoloForDream
      - name: LinkedIn
        icon: linkedin-square
        link: http://www.linkedin.com/in/rey-wang
      - name: Twitter
        icon: twitter
        link: https://twitter.com/yolofordream
      - name: WeChat
        icon: comment
        link: #

social:
  - name: GitHub
    icon: github
    link: http://github.com/YoloForDream
  - name: LinkedIn
    icon: linkedin-square
    link: http://www.linkedin.com/in/rey-wang0921
  - name: Twitter
    icon: twitter
    link: https://twitter.com/yolofordream